@defaultName = user1

### find by id
GET http://localhost:8082/users/1
Content-Type: application/json

### find by name
GET http://localhost:8082/users/name/{{defaultName}}
Content-Type: application/json

### find all
GET http://localhost:8082/users
Content-Type: application/json

### add default user
POST http://localhost:8082/users
Content-Type: application/json

{
    "name": "{{defaultName}}",
    "createAt": ""
}

### add a user
POST http://localhost:8082/users
Content-Type: application/json

{
    "name": "{{$random.name}}",
    "createAt": ""
}

### update a user
PUT http://localhost:8082/users/2
Content-Type: application/json

{
    "name": "{{$random.name}}",
    "createAt": ""
}

### delete a user
DELETE http://localhost:8082/users/2
